language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/wasdpkj/arduino-board-index/gh-pages/install.sh)
script:
  - build_platform adafruit:avr:protrinket5
  - build_platform adafruit:avr:protrinket5ftdi
  - build_platform adafruit:avr:16MHzatmega328
  - build_platform adafruit:avr:protrinket3
  - build_platform adafruit:avr:protrinket3ftdi
branches:
  only:
    - gh-pages
notifications:
  email:
    on_success: change
    on_failure: change
