language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/wasdpkj/arduino-board-index/gh-pages/install.sh)
script:
#  - build_platform core328
  - build_platform coreplus644
#  - build_platform coreplus1284
#  - build_platform coreusb
branches:
  only:
    - gh-pages
notifications:
  email:
    on_success: change
    on_failure: change
